import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar"
import TodoList from "@/components/TodoList";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Todo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className="main p-5 flex justify-between">
          <div className=" todo-list-visibility">
          <TodoList />
          </div>
       
        {children}
        </div>
        </body>
    </html>
  );
}
